### ISSUE TITLE
Is it possible to add custom headers to all requests?

### ISSUE THREAD

**Issue by aniruddhagore1984** [diladele/webproxy#219]
Hello, I was wondering if there is a way to add custom headers before Web Filtering Proxy forwards my request to the destination? I read through all the content at https://webproxy.diladele.com/docs/ but either did not find a way or could not understand it. Would really appreciate some pointers if it is possible :)

**Comment by ra-at-diladele-com** [comment]
Hello, currently it is not possible. May I ask what problem you are trying to solve by adding headers?

**Comment by aniruddhagore1984** [comment]
Hello there,

Thanks for responding. The use case is, I am running a program that makes HTTP calls via the proxy. These calls should contain certain headers (certificate based client auth), but where the device this program is running on does not have those certificate. So I was thinking if I could just put the cert on the server running the proxy and it could attach the required headers for each request.

Do you have any recommendations for awesome free proxies, like yours, that have this fetaure? 🙂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ra-at-diladele-com** [comment]
It seems you need some kind of programmable proxy. The wfp will not do the job.
