### ISSUE TITLE
SSL errors ignored?

### ISSUE THREAD

**Issue by tmann50** [diladele/webproxy#237]
When testing SSL errors using [https://badssl.com/](https://badssl.com/), several of the links that should produce an error do not produce any error when using the proxy. I'm using HTTPS inspection certificate, and the proxy seems to be providing an inspection certificate for these sites, and passing them to the client. Because the inspection cert is trusted, error is not shown.

When the proxy is not used, I get a microsoft edge SSL error.

Can the web filter not yet handle SSL errors? This seems pretty important.

(I'm running in Azure by the way)

**Comment by ra-at-diladele-com** [comment]
Thanks will now start testing.

**Comment by ra-at-diladele-com** [comment]
Added certficate checking procedures in version 1.0.0 - the https://badssl.com/dashboard/ is green. Please may I ask you to check it after the release is published?

**Comment by tmann50** [comment]
Of course!
-------- Original message --------From: "Diladele B.V." ***@***.***> Date: 17/04/2021  2:23 pm  (GMT+00:00) To: diladele/webproxy ***@***.***> Cc: tmann50 ***@***.***>, Author ***@***.***> Subject: Re: [diladele/webproxy] SSL errors ignored? (#237) 
Added certficate checking procedures in version 1.0.0 - the https://badssl.com/dashboard/ is green. Please may I ask you to check it after the release is published?

**Comment by ra-at-diladele-com** [comment]
The Admin Guide is updated, will publish on Monday but already now can install and use. See https://packages.diladele.com/webproxy/1.0.0.9D80/amd64/release/windows/webproxy-1.0.0.9D80_amd64.msi. History at https://webproxy.diladele.com/docs/versions/

**Comment by tmann50** [comment]
Is there a way of updating and keeping the previous settings?

**Comment by ra-at-diladele-com** [comment]
Depends on the age of existing version you could just copy the C:\ProgramData\diladele\webfilteringproxy\etc into some folder, uninstall the old version, install new and then overwrite the etc files. Hopefully will work.

**Comment by tmann50** [comment]
Thanks, I'll try that. I'm using the latest published version.
