### ISSUE TITLE
Settings removed

### ISSUE THREAD

**Issue by tmann50** [diladele/webproxy#249]
It seems that when adjusting the overall proxy settings, and applying settings/restarting a number of times, some of the settings reset.

It has happened to me a couple of times. Standard proxy was turned back on, secure proxy was turned off, and negotiate settings were removed.

**Comment by ra-at-diladele-com** [comment]
Any exact steps to reproduce?

**Comment by ra-at-diladele-com** [comment]
Fixed, will be included into 1.1.
