### ISSUE TITLE
Banking category

### ISSUE THREAD

**Issue by MatjazP72** [diladele/webproxy#31]
Hello!

Some Slovenian banks are not intercepted, for example https://www.nlb.si is properly excluded (site verified by Entrust), two others https://www.skb.si and https://www.nkbm.si are intercepted and decrypted (site verified by Example Ltd.).

How and where is banking category maintained? I can give you a list of all Slovenian financial instutions.

This is my config:

"exclusions" : {
                    "exclude_by_referer": false,
                    "domain_name" : [
                        { "enable" : true, "comment": "", "scan": { "adblock": false, "adult": false, "categories": false, "file": false, "http": false, "privacy": false, "decrypt" : false }, "value": ".windowsupdate.com" },
                        { "enable" : true, "comment": "", "scan": { "adblock": false, "adult": false, "categories": false, "file": false, "http": false, "privacy": false, "decrypt" : false }, "value": "download.microsoft.com" },
                        **{ "enable" : true, "comment": "", "scan": { "adblock": false, "adult": false, "categories": false, "file": false, "http": false, "privacy": false, "decrypt" : false }, "value": ".skb.si" }**
                    ],

Kind regards,
Matjaz

**Comment by ra-at-diladele-com** [comment]
Hello Matjaz, just put them all here, I will add to the definitions next week.

Best regards,
Rafael Akchurin

On 21 Sep 2020, at 17:44, MatjazP72 <notifications@github.com> wrote:

﻿

Hello!

Some Slovenian banks are not intercepted, for example https://www.nlb.si is properly excluded (site verified by Entrust), two others https://www.skb.si and https://www.nkbm.si are intercepted and decrypted (site verified by Example Ltd.).

How and where is banking category maintained? I can give you a list of all Slovenian financial instutions.

Kind regards,
Matjaz

**Comment by MatjazP72** [comment]
Here you go :) 


**Banking sites in Slovenia**

Description;Main site;Domain;
ADDIKO BANK d.d.;https://www.addiko.si;.addiko.si
BANKA INTESA SANPAOLO d.d.;https://www.intesasanpaolobank.si;.intesasanpaolobank.si
BANKA SPARKASSE d.d.;https://www.sparkasse.si;.sparkasse.si
BANKA SLOVENIJE;https://www.bsi.si;.bsi.si
DEZELNA BANKA SLOVENIJE d.d.;https://www.dbs.si;.dbs.si
GORENJSKA BANKA d.d.;https://www.gbkr.si;.gbkr.si
NOVA KREDITNA BANKA MARIBOR d.d.;https://www.nkbm.si;.nkbm.si
NOVA LJUBLJANSKA BANKA d.d.;https://www.nlb.si;.nlb.si
SBERBANK BANKA d.d.;https://www.sberbank.si;.sberbank.si
SID - SLOVENSKA IZVOZNA IN RAZVOJNA BANKA, d.d.;https://www.sid.si;.sid.si
SKB BANKA d.d.;https://www.skb.si;.skb.si
UNICREDIT BANKA SLOVENIJA d.d.;https://www.unicredit.si;.unicredit.si
Delavska hranilnica d.d.;https://www.delavska-hranilnica.si;.delavska-hranilnica.si
Hranilnica LON d.d.;https://www.lon.si;.lon.si
Primorska hranilnica Vipava d.d.;https://www.phv.si;.phv.si

**Insurance companies**

Description;Main site;Domain;
Coface PKZ zavarovalnica d.d.;http://www.sid-pkz.si;.sid-pkz.si
GENERALI ZAVAROVALNICA D.D.;http://www.generali.si;.generali.si
GRAWE ZAVAROVALNICA D.D.;http://www.grawe.si;.grawe.si
MERKUR ZAVAROVALNICA D.D.;http://www.merkur-zav.si;.merkur-zav.si
MODRA ZAVAROVALNICA D.D.;http://www.modra-zavarovalnica.si;.modra-zavarovalnica.si
MODRA ZAVAROVALNICA D.D.;http://www.modra.si;.modra.si
PRVA OSEBNA ZAVAROVALNICA D.D.;http://www.prva.net;.prva.net
TRIGLAV ZDRAVSTVENA ZAVAROVALNICA D.D.;http://www.zdravstvena.net;.zdravstvena.net
Vita, zivljenjska zavarovalnica, d.d.;https://www.zav-vita.si;.zav-vita.si
VZAJEMNA ZDRAVSTVENA ZAVAROVALNICA D.V.Z.;http://www.vzajemna.si;.vzajemna.si
ZAVAROVALNICA SAVA, d.d.;https://zav-sava.si;.zav-sava.si
ZAVAROVALNICA TRIGLAV D.D.;http://www.triglav.si;.triglav.si

**Slovenian fund management companies**

Description;Main site;Domain;
Generali Investments;https://www.generali-investments.si;.generali-investments.si
NLB Skladi;http://www.nlbskladi.si/;.nlbskladi.si
Sava Infond;https://www.infond.si;.infond.si
Triglav Skladi;https://www.triglavskladi.si;.triglavskladi.si

**Slovenian governement** 

Description;Main site;Domain;
Slovenian Government state portal;https://www.gov.si;.gov.si

**Comment by MatjazP72** [comment]
Here you go :)

Banking sites in Slovenia

Description;Main site;Domain;
ADDIKO BANK d.d.;https://www.addiko.si;.addiko.si
BANKA INTESA SANPAOLO d.d.;https://www.intesasanpaolobank.si;.intesasanpaolobank.si
BANKA SPARKASSE d.d.;https://www.sparkasse.si;.sparkasse.si
BANKA SLOVENIJE;https://www.bsi.si;.bsi.si
DEZELNA BANKA SLOVENIJE d.d.;https://www.dbs.si;.dbs.si
GORENJSKA BANKA d.d.;https://www.gbkr.si;.gbkr.si
NOVA KREDITNA BANKA MARIBOR d.d.;https://www.nkbm.si;.nkbm.si
NOVA LJUBLJANSKA BANKA d.d.;https://www.nlb.si;.nlb.si
SBERBANK BANKA d.d.;https://www.sberbank.si;.sberbank.si
SID - SLOVENSKA IZVOZNA IN RAZVOJNA BANKA, d.d.;https://www.sid.si;.sid.si
SKB BANKA d.d.;https://www.skb.si;.skb.si
UNICREDIT BANKA SLOVENIJA d.d.;https://www.unicredit.si;.unicredit.si
Delavska hranilnica d.d.;https://www.delavska-hranilnica.si;.delavska-hranilnica.si
Hranilnica LON d.d.;https://www.lon.si;.lon.si
Primorska hranilnica Vipava d.d.;https://www.phv.si;.phv.si

Insurance companies

Description;Main site;Domain;
Coface PKZ zavarovalnica d.d.;http://www.sid-pkz.si;.sid-pkz.si
GENERALI ZAVAROVALNICA D.D.;http://www.generali.si;.generali.si
GRAWE ZAVAROVALNICA D.D.;http://www.grawe.si;.grawe.si
MERKUR ZAVAROVALNICA D.D.;http://www.merkur-zav.si;.merkur-zav.si
MODRA ZAVAROVALNICA D.D.;http://www.modra-zavarovalnica.si;.modra-zavarovalnica.si
MODRA ZAVAROVALNICA D.D.;http://www.modra.si;.modra.si
PRVA OSEBNA ZAVAROVALNICA D.D.;http://www.prva.net;.prva.net
TRIGLAV ZDRAVSTVENA ZAVAROVALNICA D.D.;http://www.zdravstvena.net;.zdravstvena.net
Vita, zivljenjska zavarovalnica, d.d.;https://www.zav-vita.si;.zav-vita.si
VZAJEMNA ZDRAVSTVENA ZAVAROVALNICA D.V.Z.;http://www.vzajemna.si;.vzajemna.si
ZAVAROVALNICA SAVA, d.d.;https://zav-sava.si;.zav-sava.si
ZAVAROVALNICA TRIGLAV D.D.;http://www.triglav.si;.triglav.si

Slovenian fund management companies

Description;Main site;Domain;
Generali Investments;https://www.generali-investments.si;.generali-investments.si
NLB Skladi;http://www.nlbskladi.si/;.nlbskladi.si
Sava Infond;https://www.infond.si;.infond.si
Triglav Skladi;https://www.triglavskladi.si;.triglavskladi.si

Slovenian governement

Description;Main site;Domain;
Slovenian Government state portal;https://www.gov.si;.gov.si

**Comment by ra-at-diladele-com** [comment]
Thanks got them - will put into the definitions database for the next build.

**Comment by ra-at-diladele-com** [comment]
Added to definitions.
