### ISSUE TITLE
How to get Third-Party Certificate for Secure Proxy?

### ISSUE THREAD

**Issue by achuet** [diladele/webproxy#638]
Hi , I followed the admin guide document and want to install the third party certificate from letsencrypt. I know how to get certificates for websites using certbot ... But I couldn't find any document to get the certificate for secure proxy.

Could you please share any reference docs for that.

**Comment by Jersh** [comment]
https://webproxy.diladele.com/docs/network/secure_proxy/certificate/third_party/

This page specifically mentions using letsencrypt as a third party certificate source. You generate a certificate as you would any other web server
